/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC.Vista;

/**
 *
 * @author alejandro
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemMostrarEtiquetas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemSalirBuscador = new javax.swing.JMenuItem();
        jMenuItemApagarServidor = new javax.swing.JMenuItem();

        setMinimumSize(new java.awt.Dimension(860, 500));
        setPreferredSize(new java.awt.Dimension(860, 500));

        jMenu1.setText("Solr");

        jMenuItem1.setText("Cambiar Colección");
        jMenuItem1.setActionCommand("ViewCambiarColección");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Realizar Consulta");
        jMenuItem2.setActionCommand("ViewRealizarConsulta");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem3.setText("Consultas");
        jMenuItem3.setActionCommand("ViewAyudaConsultas");
        jMenu2.add(jMenuItem3);

        jMenuItemMostrarEtiquetas.setText("Mostrar Etiquetas");
        jMenuItemMostrarEtiquetas.setActionCommand("MostrarEtiquetas");
        jMenuItemMostrarEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMostrarEtiquetasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMostrarEtiquetas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        jMenuItemSalirBuscador.setText("Salir");
        jMenu3.add(jMenuItemSalirBuscador);

        jMenuItemApagarServidor.setText("Apagar servidor");
        jMenuItemApagarServidor.setActionCommand("ApagarServidor");
        jMenu3.add(jMenuItemApagarServidor);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemMostrarEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMostrarEtiquetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemMostrarEtiquetasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem jMenuItemApagarServidor;
    public javax.swing.JMenuItem jMenuItemMostrarEtiquetas;
    public javax.swing.JMenuItem jMenuItemSalirBuscador;
    // End of variables declaration//GEN-END:variables
}
